In [39]:
import torch

In [40]:
A = torch.arange(1, 17).view(2, 2, 1, 4)
A

tensor([[[[ 1,  2,  3,  4]],

         [[ 5,  6,  7,  8]]],


        [[[ 9, 10, 11, 12]],

         [[13, 14, 15, 16]]]])

In [41]:
B = torch.arange(1, 25).view(3, 2, 1, 4)
B

tensor([[[[ 1,  2,  3,  4]],

         [[ 5,  6,  7,  8]]],


        [[[ 9, 10, 11, 12]],

         [[13, 14, 15, 16]]],


        [[[17, 18, 19, 20]],

         [[21, 22, 23, 24]]]])

In [44]:
C = torch.einsum('ibhd,jbhd->ijbh', A, B)
C

tensor([[[[  30],
          [ 174]],

         [[ 110],
          [ 382]],

         [[ 190],
          [ 590]]],


        [[[ 110],
          [ 382]],

         [[ 446],
          [ 846]],

         [[ 782],
          [1310]]]])

In [43]:
C.shape

torch.Size([2, 3, 2, 1, 4])